apiVersion: v1
kind: Pod
metadata:
  name: aichats-frontend
  labels:
    app: aichats-frontend
    "traefik.enable": "true"
    "traefik.http.routers.aichats-frontend.rule": "Host(`pm.oujun.work`)"
    "traefik.http.routers.aichats-frontend.entrypoints": "websecure"
    "traefik.http.routers.aichats-frontend.tls.certresolver": "cloudflare"
    "traefik.http.services.aichats-frontend.loadbalancer.server.port": "80"
spec:
  containers:
    - name: aichats-frontend
      image: registry.cn-hangzhou.aliyuncs.com/geeky-explorer/aichats-frontend:latest
      env:
        - name: VITE_API_BASE_URL
          value: "https://api.oujun.work"
      ports:
        - containerPort: 80
          name: http
